oc create secret generic n8n-app-secret \
  --from-literal=DB_POSTGRESDB_USER="$POSTGRES_USER" \
  --from-literal=DB_POSTGRESDB_PASSWORD="$POSTGRES_PASSWORD" \
  --from-literal=DB_POSTGRESDB_DATABASE="$POSTGRES_DB" \
  --from-literal=QUEUE_BULL_REDIS_PASSWORD="$REDIS_PASSWORD" \
  --from-literal=N8N_ENCRYPTION_KEY="$N8N_ENCRYPTION_KEY"
